import { Database } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";
import { join } from "path";
import { renameColumnIfExists } from "./schema-utils";

// SQL migrations generated by drizzle-kit (`bun run db:generate`); shipped next to src/ (see Dockerfile).
const MIGRATIONS_FOLDER = join(import.meta.dir, "../../../drizzle/app");

// app.db — application/domain-owned: queue, resource, error_log (schema: ./schema/app.ts).
// No telegram-specific columns (see docs/diary/2026-08-22_..., audit finding #1).
export function openAppDb(dataDir: string): Database {
  const db = new Database(join(dataDir, "app.db"), { create: true });
  db.exec("PRAGMA journal_mode = WAL;");

  // Track -> Resource rename (2026-09): converts databases from before it, no-op otherwise. Must run
  // before the migrations — the baseline creates tables with the new names.
  db.transaction(() => {
    renameColumnIfExists(db, "queue", "track_id", "resource_id");
    renameColumnIfExists(db, "resource", "track_id", "resource_id");
  })();

  migrate(drizzle(db), { migrationsFolder: MIGRATIONS_FOLDER });

  return db;
}
