import { Database } from "bun:sqlite";
import { drizzle } from "drizzle-orm/bun-sqlite";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";
import { join } from "path";
import { renameColumnIfExists, renameTableIfExists } from "./schema-utils";

// SQL migrations generated by drizzle-kit (`bun run db:generate`); shipped next to src/ (see Dockerfile).
const MIGRATIONS_FOLDER = join(import.meta.dir, "../../../drizzle/telegram");

// telegram.db — telegram-owned: telegram_reply_refs, telegram_resource_refs, users
// (schema: ./schema/telegram.ts). Private zone of infra/{presentation,adapters,repository} —
// domain/application don't know this file exists.
export function openTelegramDb(dataDir: string): Database {
  const db = new Database(join(dataDir, "telegram.db"), { create: true });
  db.exec("PRAGMA journal_mode = WAL;");

  // Track -> Resource rename (2026-09): converts databases from before it, no-op otherwise. Must run
  // before the migrations — the baseline creates tables with the new names.
  db.transaction(() => {
    renameTableIfExists(db, "telegram_track_refs", "telegram_resource_refs");
    renameColumnIfExists(db, "telegram_resource_refs", "track_id", "resource_id");
  })();

  migrate(drizzle(db), { migrationsFolder: MIGRATIONS_FOLDER });

  return db;
}
